package com.myspace.forms_sample;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class MyObject implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "My Boolean")
	private java.lang.Boolean myBoolean;
	@org.kie.api.definition.type.Label(value = "My String")
	private java.lang.String myString;
	@org.kie.api.definition.type.Label(value = "My Date Time ")
	private java.time.LocalDateTime myDateTime;
	@org.kie.api.definition.type.Label(value = "My Double")
	private java.lang.Double myDouble;

	public MyObject() {
	}

	public java.lang.Boolean getMyBoolean() {
		return this.myBoolean;
	}

	public void setMyBoolean(java.lang.Boolean myBoolean) {
		this.myBoolean = myBoolean;
	}

	public java.lang.String getMyString() {
		return this.myString;
	}

	public void setMyString(java.lang.String myString) {
		this.myString = myString;
	}

	public java.time.LocalDateTime getMyDateTime() {
		return this.myDateTime;
	}

	public void setMyDateTime(java.time.LocalDateTime myDateTime) {
		this.myDateTime = myDateTime;
	}

	public java.lang.Double getMyDouble() {
		return this.myDouble;
	}

	public void setMyDouble(java.lang.Double myDouble) {
		this.myDouble = myDouble;
	}

	public MyObject(java.lang.Boolean myBoolean, java.lang.String myString,
			java.time.LocalDateTime myDateTime, java.lang.Double myDouble) {
		this.myBoolean = myBoolean;
		this.myString = myString;
		this.myDateTime = myDateTime;
		this.myDouble = myDouble;
	}

}